// Precompiles every prompts/*.njk template into plain JS ahead of time, so
// the deployed Worker never calls nunjucks' string-to-function compiler
// (which relies on `new Function(...)`) — Cloudflare Workers run untrusted
// V8 isolates and don't allow dynamic code generation at runtime. This
// mirrors how Nunjucks recommends precompiling for CSP-restricted browsers;
// same idea, same mechanism, here applied to Workers instead.
//
// Run via `npm run build:prompts` (also wired as a `pre*` hook ahead of
// `dev`/`deploy`/`typecheck` — see package.json) whenever a .njk file changes.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import nunjucks from "nunjucks";

const here = path.dirname(fileURLToPath(import.meta.url));
const promptsDir = path.join(here, "..", "prompts");
const outDir = path.join(here, "..", "src", "prompts", "generated");
const outFile = path.join(outDir, "precompiled.ts");

const templateFiles = readdirSync(promptsDir).filter((f) => f.endsWith(".njk"));

const env = new nunjucks.Environment([]);
const compiled = templateFiles.map((name) => {
  const src = readFileSync(path.join(promptsDir, name), "utf8");
  return nunjucks.precompileString(src, {
    name,
    env,
    // Emits just the template's compiled function body, so we can wrap it
    // ourselves into a plain ESM export below (no `window` global, no eval).
    wrapper: (templates) => templates[0].template,
  });
});

let out = `// AUTO-GENERATED by scripts/precompile-prompts.mjs from prompts/*.njk — do not edit by hand.\n`;
out += `// @ts-nocheck\n\n`;
out += `export const precompiledTemplates: Record<string, unknown> = {\n`;
templateFiles.forEach((name, i) => {
  out += `  ${JSON.stringify(name)}: (function() {\n${compiled[i]}\n  })(),\n`;
});
out += `};\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, out);
console.log(`Precompiled ${templateFiles.length} prompt template(s) -> ${path.relative(process.cwd(), outFile)}`);
