// Precompiles every prompts/*.njk template into plain JS ahead of time, so
// the deployed Worker never calls nunjucks' string-to-function compiler
// (which relies on `new Function(...)`) — Cloudflare Workers run untrusted
// V8 isolates and don't allow dynamic code generation at runtime. This
// mirrors how Nunjucks recommends precompiling for CSP-restricted browsers;
// same idea, same mechanism, here applied to Workers instead.
//
// Run via `npm run build:prompts` (also wired as a `pre*` hook ahead of
// `dev`/`deploy`/`typecheck` — see package.json) whenever a .njk file changes.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import nunjucks from "nunjucks";

const here = path.dirname(fileURLToPath(import.meta.url));
const promptsDir = path.join(here, "..", "prompts");
const outDir = path.join(here, "..", "src", "prompts", "generated");
const outFile = path.join(outDir, "precompiled.ts");

const env = new nunjucks.Environment([]);

/**
 * Compiles one template to its function body. Line endings are normalised to
 * LF first: a Windows checkout with core.autocrlf=true has CRLF templates, and
 * nunjucks keeps them, so the prompts sent to the model (and the snapshots in
 * explanation-prompt.test.mjs) came out with \r\n on one machine and \n on
 * another. .gitattributes also checks the templates out as LF.
 */
export function compileTemplate(name, src) {
  return nunjucks.precompileString(src.replace(/\r\n?/g, "\n"), {
    name,
    env,
    // Emits just the template's compiled function body, so we can wrap it
    // ourselves into a plain ESM export below (no `window` global, no eval).
    wrapper: (templates) => templates[0].template,
  });
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const templateFiles = readdirSync(promptsDir).filter((f) => f.endsWith(".njk"));
  const compiled = templateFiles.map((name) => compileTemplate(name, readFileSync(path.join(promptsDir, name), "utf8")));

  let out = `// AUTO-GENERATED by scripts/precompile-prompts.mjs from prompts/*.njk — do not edit by hand.\n`;
  out += `// @ts-nocheck\n\n`;
  out += `export const precompiledTemplates: Record<string, unknown> = {\n`;
  templateFiles.forEach((name, i) => {
    out += `  ${JSON.stringify(name)}: (function() {\n${compiled[i]}\n  })(),\n`;
  });
  out += `};\n`;

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, out);
  console.log(`Precompiled ${templateFiles.length} prompt template(s) -> ${path.relative(process.cwd(), outFile)}`);
}
