// Renders docs/requirements/ai-explanations.md's AI-explanation prompt from a Nunjucks (Jinja2-syntax)
// template — see apps/worker/prompts/explanation.njk. Only ever renders
// *precompiled* templates (generated by scripts/precompile-prompts.mjs into
// prompts/generated/precompiled.ts): Cloudflare Workers run untrusted V8
// isolates and disallow dynamic code generation, and nunjucks' normal
// string-to-function compiler relies on `new Function(...)` to do that.
// PrecompiledLoader bypasses the compiler entirely — the "code" it returns
// is already a plain JS object, not a string to eval.

import nunjucks from "nunjucks";
import { precompiledTemplates } from "../prompts/generated/precompiled";

// @types/nunjucks types PrecompiledLoader's constructor param as `any[]`,
// but at runtime it's actually a { [templateName]: compiledTemplate } map
// (see node_modules/nunjucks/src/precompiled-loader.js) — the type itself is
// simply wrong here, hence the cast.
const env = new nunjucks.Environment(new nunjucks.PrecompiledLoader(precompiledTemplates as any), {
  autoescape: false, // this feeds an LLM prompt, not HTML — don't entity-escape it
});

export interface ExplanationPromptContext {
  stem: string;
  options: { id: string; text: string }[];
  correctAnswers: string[];
  officialExplanation: string | null;
}

export function renderExplanationPrompt(ctx: ExplanationPromptContext): string {
  return env.render("explanation.njk", ctx);
}
