// Renders docs/requirements/ai-explanations.md's AI-explanation prompt from a Nunjucks (Jinja2-syntax)
// template — see apps/worker/prompts/explanation.njk. Only ever renders
// *precompiled* templates (generated by scripts/precompile-prompts.mjs into
// prompts/generated/precompiled.ts): Cloudflare Workers run untrusted V8
// isolates and disallow dynamic code generation, and nunjucks' normal
// string-to-function compiler relies on `new Function(...)` to do that.
// PrecompiledLoader bypasses the compiler entirely — the "code" it returns
// is already a plain JS object, not a string to eval.

import nunjucks from "nunjucks";
import { precompiledTemplates } from "../prompts/generated/precompiled";

// @types/nunjucks types PrecompiledLoader's constructor param as `any[]`,
// but at runtime it's actually a { [templateName]: compiledTemplate } map
// (see node_modules/nunjucks/src/precompiled-loader.js) — the type itself is
// simply wrong here, hence the cast.
const env = new nunjucks.Environment(new nunjucks.PrecompiledLoader(precompiledTemplates as any), {
  autoescape: false, // this feeds an LLM prompt, not HTML — don't entity-escape it
});

export interface ExplanationPromptContext {
  stem: string;
  // Which instructions fit (issue #42): "choice" asks about the other options,
  // while matching and ordering have no wrong options, only wrong pairings or
  // positions, and a fill-in has no options at all.
  kind: "choice" | "text" | "ordering" | "matching";
  // A matching question's left column, or the items to order, or the choices.
  options: { id: string; text: string }[];
  // A matching question's right column; empty otherwise.
  matchTargets: { id: string; text: string }[];
  // Readable lines for matching and ordering ("HTTPS → 443"); IDs or accepted
  // answers otherwise.
  correctAnswers: string[];
  officialExplanation: string | null;
  // The stem carries figure captions and alt text only.
  figureOmitted: boolean;
}

export function renderExplanationPrompt(ctx: ExplanationPromptContext): string {
  return env.render("explanation.njk", ctx);
}
